# fly.toml app configuration file generated for lustre-fullstack on 2024-12-12T12:39:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lustre-fullstack'
primary_region = 'lhr'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
